// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRPERHNulN04dksbXR1OskaOM45JpmdpM',
    appId: '1:765780426974:web:b1de9474465c661de2424f',
    messagingSenderId: '765780426974',
    projectId: 'reservas-golf-910a5',
    authDomain: 'reservas-golf-910a5.firebaseapp.com',
    storageBucket: 'reservas-golf-910a5.firebasestorage.app',
    measurementId: 'G-XHS6VNDMYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRRYjPN3ICg6pmXMe7WnwIAUUCVDZZLY',
    appId: '1:765780426974:android:da5d037e0ba1752de2424f',
    messagingSenderId: '765780426974',
    projectId: 'reservas-golf-910a5',
    storageBucket: 'reservas-golf-910a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwJ9_Rkm7f_2AEa7MedmlpLr2T2oqQOwI',
    appId: '1:765780426974:ios:e4937dc830812697e2424f',
    messagingSenderId: '765780426974',
    projectId: 'reservas-golf-910a5',
    storageBucket: 'reservas-golf-910a5.firebasestorage.app',
    iosBundleId: 'com.example.reservasGolf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwJ9_Rkm7f_2AEa7MedmlpLr2T2oqQOwI',
    appId: '1:765780426974:ios:e4937dc830812697e2424f',
    messagingSenderId: '765780426974',
    projectId: 'reservas-golf-910a5',
    storageBucket: 'reservas-golf-910a5.firebasestorage.app',
    iosBundleId: 'com.example.reservasGolf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRPERHNulN04dksbXR1OskaOM45JpmdpM',
    appId: '1:765780426974:web:b0bba4ad129cac85e2424f',
    messagingSenderId: '765780426974',
    projectId: 'reservas-golf-910a5',
    authDomain: 'reservas-golf-910a5.firebaseapp.com',
    storageBucket: 'reservas-golf-910a5.firebasestorage.app',
    measurementId: 'G-TL4ZZY0MRE',
  );
}
